#!/bin/sh -ux

COMMON_AUTH_TEMP=$(mktemp -p /tmp common-auth.XXX)

# save original settings
if [ ! -f /etc/pam.d/common-auth.orig ]; then
	cp -v /etc/pam.d/common-auth /etc/pam.d/common-auth.orig;
fi

awk -v common_auth=/etc/pam.d/common-auth -v common_auth_temp=$COMMON_AUTH_TEMP '
BEGIN {
	nskip_modules = 0;
	has_nullok = 0;
	while ((getline < common_auth) > 0) {
		if (($0 ~ /^#/) || ($0 ~ /^$/)) continue;
		if ($0 ~ /.*nullok[^_]+|.*nullok$/) { has_nullok = 1; }
		if ($0 !~ /pam_permit.so/) { nskip_modules++; }
	}
	if (has_nullok) {
		system("rm -v " common_auth_temp);
		printf("/etc/pam.d/common-auth already has nullok module\n");
		exit 0;
	}
}
$1 ~ /auth/ && has_nullok == 0 {
	printf("auth\t[success=%d default=ignore]\tpam_unix.so nullok\n", nskip_modules) >> common_auth_temp;
	print >> common_auth_temp;
	has_nullok = 1;
	next;
} 
{ print >> common_auth_temp; }
' /etc/pam.d/common-auth

[ -f $COMMON_AUTH_TEMP ] && cp -v $COMMON_AUTH_TEMP /etc/pam.d/common-auth

SSHD_CONF=/etc/ssh/sshd_config

if [ -f $SSHD_CONF ]; then
	sed -E -i 's/^#PermitEmptyPasswords .*$/PermitEmptyPasswords yes/g' $SSHD_CONF 
fi
